services:
  angular-dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4200:4200'
    environment:
      - API_URL=http://localhost:5000/api
    command: yarn start --host 0.0.0.0 --port 4200
